repos:
  - repo: local
    hooks:
      - id: baseline-warden
        name: baseline-warden
        entry: bw scan --dry-run --out console --config baseline-warden.toml
        language: system
        files: '\\.(html|htm|jinja|jinja2|css)$'
