name: Baseline Warden

on:
  pull_request:
  push:
    branches: [main]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: pip install baseline-warden
      - run: bw sync --lock
      - run: bw scan --ci --config baseline-warden.toml --out console,json,gh-annotations
      - uses: actions/upload-artifact@v4
        with:
          name: baseline-warden-report
          path: report.json
        if: always()
